[version]
root_package = "package.json"
cargo_manifest_paths = ["crates/verso/Cargo.toml"]

[workspaces]
patterns = ["packages/*"]
include_root = false

[changelog]
enabled = true
infile = "CHANGELOG.md"

[git]
commit_message = "chore(release): release v${version}"
tag_name = "v${version}"
